//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace StahrDar {
    
    
    public partial class UpdateClasses {
        protected global::System.Web.UI.WebControls.Label lblUser;
    }
}
